version: "3"
services:
  db:
    image: postgres:14.1-alpine
    container_name: test_task_db
    env_file: docker/.dockerenv
    restart: always
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - DEBUG=${DEBUG}
    container_name: test_task_app
    env_file: docker/.dockerenv
    restart: always
    volumes:
      - ./src:/src
      - ./volumes/media:/media
      - ./volumes/static:/src/staticfiles
    depends_on:
      - db
      - redis
    command: gunicorn --bind 0.0.0.0:8000 --timeout 600 --log-level debug --reload
      --workers 4 config.wsgi:application

  nginx:
    image: nginx:1.21.4-alpine
    container_name: test_task_nginx
    restart: always
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./volumes/static:/var/www/static
      - ./volumes/media:/var/www/media
    depends_on:
      - app
    ports:
      - "80:80"

  redis:
    image: redis:5-alpine

  celery:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - DEBUG=${DEBUG}
    container_name: test_task_celery
    restart: always
    command: celery worker -A config -l info -B -c 4
    volumes:
      - ./src:/src
    env_file:
      - docker/.dockerenv
    depends_on:
      - app
      - redis
